config/routes.rb
Rails.application.routes.draw do

  root 'lab#index'

  get 'creatures' => 'creatures#index'

  resources :creatures
  resources :tags

end

app/models/creature.rb
class Creature < ActiveRecord::Base
  has_and_belongs_to_many :tags
end

app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :creatures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

  def index
    @creatures = Creature.all
  end

  def new
    @creature = Creature.new
    @tags = Tag.all
  end

  def create
    c = Creature.create(creature_params)
    update_tags c
    redirect_to creatures_path
  end

  def destroy
    @c = Creature.find(params[:id])
    @c.destroy
    redirect_to creatures_path
  end

  def edit
    @creature = Creature.find params[:id]
    @tags = Tag.all
  end

  def show
    @creature = Creature.find params[:id]
  end

  def update
    c = Creature.find params[:id]
    c.update creature_params
    c.tags.clear
    update_tags c
    redirect_to c
  end

  private

  def update_tags creature
    creature_tags = params[:creature][:tag_ids]
    creature_tags.each do |id|
      creature.tags << Tag.find(id) unless id.blank?
    end
  end



  def creature_params
    params.require(:creature).permit(:name,:description)
  end

end

app/controllers/lab_controller.rb
class LabController < ApplicationController

  def index
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

def index
  @tags = Tag.all
end

def new
  @tag = Tag.new
end

def create
  t = Tag.create(tag_params)
  redirect_to creatures_path
end

def edit
  @tag = Tag.find params[:id]
end

def destroy
   t = Tag.find(params[:id])
   assoc = t.creatures.length
  if t.creatures.empty?
    t.destroy
  else
    flash[:danger] = "You can not delete this tag because #{assoc} creatures are associated with it."
  end
  redirect_to tags_path
end

def show
  @tag = Tag.find params[:id]
end

def update
  t = Tag.find params[:id]
  t.update tag_params
  redirect_to tags_path
end

private

def tag_params
   params.require(:tag).permit(:name)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creature_helper.rb
module CreatureHelper
end

app/helpers/lab_helper.rb
module LabHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/creatures/edit.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'><h3>Edit Creature Record</h3>

<%= bootstrap_form_for @creature do |record| %>
<%= record.text_field :name %>
<%= record.text_field :description %>
<%= record.collection_check_boxes :tag_ids, @tags, :id, :name %>
<%= record.primary %>
<% end %>

</div>

</div>

app/views/creatures/index.html.erb
<div class='row'>

  <div class='col-md-8 col-md-offset-2'>

  <h4>Records To Date:</h4>

  <% @creatures.each do |c| %>

  <div class="well">
    <h4><%= c.name %></h4>
    <p>Description: <%= c.description %></p>

    <%= link_to "", edit_creature_path(c), class: 'btn btn-xs btn-primary glyphicon glyphicon-pencil pull-right' %>
    <%= link_to "", c, method: :delete, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right' %>

    <p> Tags: <% c.tags.each do |tag| %> <%= link_to tag.name, tag %><% end %></p>
    <%= link_to "Full Record", c %>
  </div>

<% end %>

  </div>

</div>

app/views/creatures/new.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>

<%= bootstrap_form_for @creature do |record| %>
<%= record.text_field :name %>
<%= record.text_field :description %>
<%= record.collection_check_boxes :tag_ids, @tags, :id, :name%>
<%= record.primary %>
<% end %>

  </div>
</div>

app/views/creatures/show.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>

<%= link_to "&larr; back".html_safe, creatures_path %>

<div class="well">
    <h4><%= @creature.name %></h4>
    <p>Description: <%= @creature.description %></p>

    <%= link_to "", edit_creature_path(@creature), class: 'btn glyphicon glyphicon-pencil pull-right' %>
    <%= link_to "", @creature, method: :delete, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right' %>
    <p> Tags: <% @creature.tags.each do |tag| %> <%= link_to tag.name, tag %><% end %></p>
    <p>Logged At: <%= @creature.created_at %></p>
</div>

  </div>
</div>

app/views/lab/index.html.erb
<div class='row'>

  <div class='col-md-8 col-md-offset-2'>

<!-- <div class='founders'>
    <div class='col-md-4'>
      <img src='http://i.livescience.com/images/i/000/023/775/original/051111_darwin_portrait_02.jpg?1327096404'>
    </div>
    <div class='col-md-4'>
      <img src='http://www.post-gazette.com/image/2014/05/24/ca0,44,1450,1494/20140524Carson.jpg'>
    </div>
    <div class='col-md-4'>
      <img src='https://www.anbg.gov.au/biography/biog-pics/linnaeus.jpg'>
    </div>
</div> -->

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Peat Project</title>

  <!-- Latest compiled and minified CSS & JS -->
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<div class='row'>
  <div class='col-md-8 col-md-offset-2'>
  <%= link_to "Home",root_path %> |
  <%= link_to "Project Records",creatures_path %> |
  <%= link_to "Record Findings",new_creature_path %> |
  <%= link_to "Add Tag",new_tag_path %> |
  <%= link_to "Tags",tags_path %>

  <h1> The Peat Project </h1>
  <p>The Peat Project is a community effort to explore our nearby peat bogs and make a record
  of the organisms living there. Started by local field biologists in 2012, the Peat Project
  hopes to use the eyes of the community to get a better understanding of this complex ecosystem.
  Thank you for your support!</p>

  </div>
</div>
<%= yield %>

</body>
</html>

app/views/tags/edit.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>

<%= bootstrap_form_for @tag do |t| %>
<%= t.text_field :name %>
<%= t.primary %>
<% end %>

  </div>
</div>

app/views/tags/index.html.erb
<div class='row'>

  <div class='col-md-8 col-md-offset-2'>

  <h4>Current Tags:</h4>

  <% flash.each do |k,v| %>
  <div class="alert alert-<%= k %>">
    <%= v %>
  </div>
<% end %>

  <% @tags.each do |t| %>

  <div class="well">
    <%= t.name %>
    <%= link_to "", edit_tag_path(t), class: 'btn btn-xs btn-primary glyphicon glyphicon-pencil pull-right' %>
    <%= link_to "", t, method: :delete, class: 'btn btn-xs btn-danger glyphicon glyphicon-trash pull-right' %>
  </div>

<% end %>

  </div>

</div>

app/views/tags/new.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>

<%= bootstrap_form_for @tag do |t| %>
<%= t.text_field :name %>
<%= t.primary %>
<% end %>

  </div>
</div>

app/views/tags/show.html.erb
<div class='row'>
  <div class='col-md-8 col-md-offset-2'>

<%= link_to "&larr; back".html_safe, tags_path %>

  <div class="well">
    <p><%= @tag.name %></p>
    <p>Creatures: <% @tag.creatures.each do |t| %> <%= link_to t.name, t %><%end%></p>
  </div>

  </div>
</div>